### ISSUE TITLE
OSError: Unable to open file (file signature not found)

### ISSUE THREAD

**Issue by pcy190** [idealo/image-super-resolution#23] opened 2019-05-05 12:10 UTC
When I run this sample Usage 
```
import numpy as np
from PIL import Image

img = Image.open(r'MyJPG_Path')
lr_img = np.array(img)

from ISR.models import RDN

rdn = RDN(arch_params={'C':6, 'D':20, 'G':64, 'G0':64, 'x':2})
rdn.model.load_weights('weights/sample_weights/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')
sr_img = rdn.predict(lr_img)
Image.fromarray(sr_img)
```
It warns that:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    rdn.model.load_weights('weights/sample_weights/rdn-C6-D20-G64-G064-x2/ArtefactCancelling/rdn-C6-D20-G64-G064-x2_ArtefactCancelling_epoch219.hdf5')
  File "lib\site-packages\keras\engine\network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "lib\site-packages\h5py\_hl\files.py", line 394, in __init__
    swmr=swmr)
  File "lib\site-packages\h5py\_hl\files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)
```
I use  the original hdf5 file which is downloaded from the Github source. I wonder how to cope with this problem.

**Comment by cfrancesco** [comment] 2019-05-06 07:19
Duplicate of #21

**Closed by cfrancesco** 2019-05-06 07:19 UTC

**Comment by pldeepesh** [comment] 2019-10-09 10:20
@cfrancesco  I have tried to use `git lfs pull` but it throws an errror,

`batch response: This repository is over its data quota. Purchase more data packs to restore access.                                                                                                         
error: failed to fetch some objects from 'https://github.com/idealo/image-super-resolution.git/info/lfs'`

**Comment by joys8998** [comment] 2020-04-02 16:54
@cfrancesco Sorry but i get the same error by trying to download weights with git lfs pull command. And i can't use the newest way to load weights (RRDN(weights='gans')) since i want to perform image resolution on a whole directory.

How can i solve?

**Comment by cfrancesco** [comment] 2020-04-02 17:37
I see. You're trying to use the predictor class. It is not maintained, it will probably be removed.

If this is your issue, then it's easy to script: model that way and then iterate through a given directory, something like
`
[code]
from pathlib import Path
rrdn = RRDN(weights='gans')
dir_path = Path('/your/img/dir/path')
out_dir_path = Path('output/dir/')

for image in dir_path.iterdir(): 
   if image.endswith('.png'): # or whatever format you have
      image = imageio.imread( dir_path/ image )
      sr_img = rrdn.predict(np.array(image))
      out_image_path = out_dir_path / image
      imageio.imwrite(out_image_path, sr_img)
    
`

**Comment by joys8998** [comment] 2020-04-02 19:43
Yeps, but the amount of images is quite huge and it chashes if i use a for cycle ( also in colab) anyway thank you for your support :)
